-- return {
-- 	{
-- 		"seblyng/roslyn.nvim",
-- 		config = function()
-- 			require("roslyn").setup({
-- 			})
-- 			vim.filetype.add({
-- 				extension = {
-- 					razor = "razor",
-- 					cshtml = "razor",
-- 				},
-- 			})
--
-- 			vim.lsp.config("roslyn", {
--
-- 			})
-- 		end
-- 	}
-- }
--
return {}
